### ISSUE TITLE
Map Values from proto are misplaced after decoding in logstash

### ISSUE THREAD

**Issue by invis87** [logstash-plugins/logstash-codec-protobuf#17] opened 2018-02-02 17:25 UTC
I've found an issue: https://github.com/logstash-plugins/logstash-codec-protobuf/issues/8 and looks like it is my case, but it is closed, so open new one.

So, the problem: **logstash-codec-protobuf doesn't work with new logstash**.

My protobuf file:
```
syntax = "proto3";

package some.package;

message VariableResult {
    string name                              = 1;
    map<string, string> identities           = 2;

    string value                             = 3;
    string message                           = 4;
    string status                            = 5;
}

message RouterResults {
    string trace_id                          = 1;
    repeated VariableResult attributes       = 2;
    repeated string requested_variables      = 3;

    repeated VariableResult results          = 4;
    int64 request_time                       = 5;
    int64 response_time                      = 6;
    map<string, string> request_tags         = 7;
}
```

Next steps:

1.  `ruby-protoc MyProto.proto` and place result file (`MyProto.pb.rb`) to `/work/logstash/config/` directory.
2. write your `logstash.conf` file and place it to `/work/logstash/config/`
3. Create `Dockerfile` with  text 
```
FROM logstash:2.3.4

RUN logstash-plugin install logstash-codec-protobuf

RUN logstash-plugin install logstash-codec-rubydebug

RUN logstash-plugin install logstash-output-kafka 

RUN logstash-plugin install logstash-input-kafka 

RUN logstash-plugin install logstash-output-stdout
	
RUN logstash-plugin install logstash-codec-plain

CMD ["-f", "/some/config/logstash.conf", "--debug"]
```
4. build it `docker build -t my-logstash .`
5. run it `docker run -i --rm --name logstash -v /work/logstash/config/:/some/config/ my-logstash`

What Happens? yep - all works fine!
Now, change **FROM logstash:2.3.4** to **FROM logstash:latest** in `Dockerfile`, build new container and run it. You will see some problems with decoding. This is how it looks for me:

Part of event deserialized with logstash:2.3.4:
```
"results"=>[{:name=>"somesecretname", :identities=>[{:key=>"somesecretkey", :value=>"rXT/T8VWO8k="}], :value=>"0.0", :status=>"SUCCESS"}, {:name=>"somesecretname1", :identities=>[{:key=>"somesecretkey", :value=>"+udxxziCmoY="}], :status=>"NOT_FOUND"}, {:name=>"somesecretname", :identities=>[{:key=>"somesecretkey", :value=>"+udxxziCmoY="}], :value=>"2848.0", :status=>"SUCCESS"}, {:name=>"somesecretname", :identities=>[{:key=>"somesecretkey", :value=>"rXT/T8VWO8k="}], :value=>"0.2597402597402597", :status=>"SUCCESS"}, {:name=>"somesecretname", :identities=>[{:key=>"somesecretkey", :value=>"3"}], :value=>"0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.75, 1.6, 2.0, 2.8333333333333335, 3.5, 4.0, 4.625, 5.0, 6.0, 6.714285714285714, 7.142857142857143, 8.0, 8.75, 9.285714285714286, 10.0, 10.8, 11.5, 12.0, 12.88888888888889, 13.4, 14.0, 14.8, 15.428571428571429, 16.142857142857142, 17.0, 17.5, 18.0, 18.875, 19.444444444444443, 20.11111111111111, 20.875, 21.6, 22.1, 23.0, 23.666666666666668, 24.25, 25.1, 25.8, 26.428571428571427, 27.2, 28.0, 28.75, 29.5, 30.25, 31.1, 31.875, 32.625, 33.5, 34.333333333333336, 35.1, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.1, 45.42857142857143, 46.6, 47.9, 49.2, 50.6, 52.25, 53.8, 55.285714285714285, 57.333333333333336, 59.125, 61.5, 63.666666666666664, 66.25, 68.85714285714286, 72.33333333333333, 75.9, 80.16666666666667, 85.0, 92.0, 100.0, 113.0, 134.5, 202.0", :status=>"SUCCESS"}, {:name=>"somesecretname", :ide
```

Part of event deserialized with logstash:latest:
```
"results"=>[{"name"=>"somesecretname", "identities"=>[{"value"=>"83", "key"=>"somesecretkey"}], "value"=>"0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 7.0, 7.0, 7.0, 7.0, 7.0, 8.0, 8.0, 8.0, 9.0, 9.0, 10.0, 10.0, 11.0, 12.0, 13.0, 15.0, 19.0*\aSUCCESS\"T\n'somesecretname\u0012\e\n\vsomesecretkey\u0012\f4nHmfILT+1Q=\u001A\u00030.5*\aSUCCESS\"g\n+somesecretname\u0012\e\n\vsomesecretkey\u0012\fCxhl935q35k=\u001A\u00121.0666666666666667*\aSU
```

As you can see if `VariableResult.value` is a long string (maybe this is not the reason) we catch some bug with deserialization.

**Comment by IngaFeick** [comment] 2018-02-06 10:49
Hi. The current version does not support protobuf 3 yet. I am working on a new version right now though and that might solve your issue. Let me come back to you at the end of the week with an update, okay?

**Comment by invis87** [comment] 2018-02-06 10:56
@IngaFeick wow, good news! Thanks and good luck)

**Comment by invis87** [comment] 2018-02-09 11:05
@IngaFeick Hi! How update is going on?

**Comment by IngaFeick** [comment] 2018-02-09 11:17
Hi! Short delay on my side due to some unexpected workload elsewhere but still on the top of my todo list. Will probably finish the PR on monday or tuesday next week. Sorry for the delay!

**Comment by invis87** [comment] 2018-02-14 08:06
@IngaFeick Hi! How are you :) ?

**Comment by IngaFeick** [comment] 2018-02-17 21:17
@invis87 doing great, you? Here's a new version for you to test:
https://rubygems.org/gems/logstash-codec-protobuf/versions/1.0.5
Here's my [branch](https://github.com/IngaFeick/logstash-codec-protobuf/tree/google-pb-lib) in case you're interested in the gory details, but this is probably sufficient for you: in your logstash input section, use the codec like so: 
```codec => protobuf 
    {
      class_name => "Module.AnotherModule.Classname"
      include_path => ['file1_pb.rb','file2_pb.rb',file3_pb.rb']
      protobuf_version_3 => true
    }
```
Let me know how that works for you! I haven't tested the map feature yet but I'd be happy to look into that tomorrow before I send the PR on its way, in case you find any problems. Cheers!

**Comment by invis87** [comment] 2018-02-19 09:25
@IngaFeick With changes in Dockerfile `RUN logstash-plugin install --version 1.0.5 logstash-codec-protobuf`
Logstash dont even start:
```
09:21:49.034 [LogStash::Runner] ERROR logstash.plugins.registry - Problems loading a plugin with {:type=>"codec", :name=>"protobuf", :path=>"logstash/codecs/protobuf", :error_message=>"NameError", :error_class=>NameError, :error_backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:226:in `namespace_lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:162:in `legacy_lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:138:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:180:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:103:in `plugin'", "(eval):8:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:75:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:165:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:296:in `create_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:313:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
09:21:49.035 [LogStash::Runner] DEBUG logstash.plugins.registry - Problems loading the plugin with {:type=>"codec", :name=>"protobuf"}
09:21:49.041 [LogStash::Runner] ERROR logstash.agent - Cannot create pipeline {:reason=>"Couldn't find any codec plugin named 'protobuf'. Are you sure this is correct? Trying to load the protobuf codec plugin resulted in this error: Problems loading the requested plugin named protobuf of type codec. Error: NameError NameError", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:185:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:103:in `plugin'", "(eval):8:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:75:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:165:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:296:in `create_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:313:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
09:21:49.048 [Ruby-0-Thread-3: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/task.rb:22] DEBUG logstash.agent - starting agent
09:21:49.052 [LogStash::Runner] DEBUG logstash.instrument.periodicpoller.os - PeriodicPoller: Stopping
09:21:49.053 [LogStash::Runner] DEBUG logstash.instrument.periodicpoller.jvm - PeriodicPoller: Stopping
09:21:49.054 [LogStash::Runner] DEBUG logstash.instrument.periodicpoller.persistentqueue - PeriodicPoller: Stopping
09:21:49.054 [LogStash::Runner] DEBUG logstash.instrument.periodicpoller.deadletterqueue - PeriodicPoller: Stopping
```

(with version 1.0.3 all works as I describe in 1st message, no other changes was made)

**Comment by invis87** [comment] 2018-03-01 13:36
@IngaFeick Can you take a look please?

**Comment by IngaFeick** [comment] 2018-03-02 07:34
@invis87 sorry, I am currently out of office for a couple of days. I will look into it as soon as I am back, promised!

**Comment by IngaFeick** [comment] 2018-03-02 07:34
@invis87 sorry, I am currently out of office for a couple of days. I will look into it asap as soon as I am back, promised!

**Comment by invis87** [comment] 2018-03-12 07:57
@IngaFeick Hello! Looks like you forget about this issue :(

**Comment by IngaFeick** [comment] 2018-03-12 10:34
@invis87  Hi there. I promise you I did not, I just came back into the office today :)
I submitted a PR a couple of days ago, https://github.com/logstash-plugins/logstash-codec-protobuf/pull/18
It might solve your issues, we tested it with logstash version 6. I haven't published the gem yet. Do you know how to build it? If not I can do that for you.

**Comment by invis87** [comment] 2018-03-12 11:04
@IngaFeick Ohh, so there is already an issue for protobuf3 and looks like my bug is about this. Cool.
No, I don't how to build, and probably better to wait for gem :)

**Comment by IngaFeick** [comment] 2018-03-16 12:40
@invis87 the PR has not been built yet so I have uploaded a preliminary version of it to dropbox. You should be able to download it (here)[https://www.dropbox.com/s/1f4cpzu7i78crhz/logstash-codec-protobuf-1.1.0.gem?dl=0] and then you install it by running 
```
logstash-plugin install  /your_downloads/logstash-codec-protobuf-1.1.0.gem
```
Please note also the changed configuration section, it's in the documentation of the pull request mentioned above. Let me know if it works, thank you!

**Comment by invis87** [comment] 2018-03-19 15:27
@IngaFeick cool!
Oh, I check new gem and... it is not working :)
With `protobuf_version => 3` I've got:
```
12:59:10.261 [LogStash::Runner] WARN  logstash.codecs.protobuf - Error 3: unable to read pb definition from file  /some/config/MySuperProto.pb.rb. Reason: #<NoMethodError: undefined method `[]=' for nil:NilClass>. Last settings were: class  field string type message. Backtrace: ["/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:324:in `pb3_metadata_analyis'", 
"org/jruby/RubyArray.java:1613:in `each'", 
"/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:313:in `pb3_metadata_analyis'", 
"/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:428:in `load_protobuf_definition'", 
"/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:97:in `register'", 
"org/jruby/RubyArray.java:1613:in `each'", 
"/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:97:in `register'", 
"/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:20:in `initialize'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:112:in `plugin'", 
"(eval):8:in `initialize'", 
"org/jruby/RubyKernel.java:1079:in `eval'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:75:in `initialize'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:165:in `initialize'", 
"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:296:in `create_pipeline'", 
"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", 
"/usr/share/logstash/logstash-core/lib/logstash/runner.rb:313:in `execute'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", 
"/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", 
"/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]
```

**Comment by IngaFeick** [comment] 2018-03-21 09:31
@invis87 can you please do an 'ls -la ' on the file mentioned in the error message (such as /some/config/MySuperProto.pb.rb ) and give me the output of that, also I need your current logstash config please and the actual protobuf definition file (ruby version). Thank you

**Comment by invis87** [comment] 2018-03-21 09:58
@IngaFeick 
First of all I want to say that If I remove `protobuf_version => 3` from logstash config  - it working, fail on deserealisation, but works at least :) So there is no probles with access to file.
1)
``` 
root@1a5f88baab92:/# ls -la /some/config/MySuperProto.pb.rb
-rw-r--r-- 1 root root 2647 Mar 19 12:34 /some/config/MySuperProto.pb.rb
```
2) logstash config: 
```
input {
    kafka {
        type => "${topic_name}"
        codec => protobuf {
            class_name => "My::Super::ClassName"
            include_path => ['/some/config/MySuperProto.pb.rb']
            protobuf_version => 3
        }
        bootstrap_servers => "{kafka_ip}:9092"
        topics => ['${topic_name}']
        group_id => "${topic_name}_consumer_group"
        consumer_threads => 1
    }
}

output {
    if [type] == "${topic_name}" {
        stdout {
            codec => plain
        }
        
    }
}
```

3) MySuperProto.pb.rb:
```
#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module My
  module Super
    module ClassName
      # forward declarations
      class VariableResult < ::ProtocolBuffers::Message; end
      class RouterResults < ::ProtocolBuffers::Message; end

      class VariableResult < ::ProtocolBuffers::Message
        # forward declarations
        class IdentitiesEntry < ::ProtocolBuffers::Message; end

        set_fully_qualified_name "my.package.name.VariableResult"

        # nested messages
        class IdentitiesEntry < ::ProtocolBuffers::Message
          set_fully_qualified_name "my.package.name.VariableResult.IdentitiesEntry"

          optional :string, :key, 1
          optional :string, :value, 2
        end

        optional :string, :name, 1
        repeated ::My::Super::ClassName::VariableResult::IdentitiesEntry, :identities, 2
        optional :string, :value, 3
        optional :string, :message, 4
        optional :string, :status, 5
      end

      class RouterResults < ::ProtocolBuffers::Message
        # forward declarations
        class RequestTagsEntry < ::ProtocolBuffers::Message; end

        set_fully_qualified_name "my.package.name.RouterResults"

        # nested messages
        class RequestTagsEntry < ::ProtocolBuffers::Message
          set_fully_qualified_name "my.package.name.RouterResults.RequestTagsEntry"

          optional :string, :key, 1
          optional :string, :value, 2
        end

        optional :string, :trace_id, 1
        repeated ::My::Super::ClassName::VariableResult, :attributes, 2
        repeated :string, :requested_variables, 3
        repeated ::My::Super::ClassName::VariableResult, :results, 4
        optional :int64, :request_time, 5
        optional :int64, :response_time, 6
        repeated ::My::Super::ClassName::RouterResults::RequestTagsEntry, :request_tags, 7
      end
    end
  end
end
```
---
I edit class by hands to remove company data, so mistakes may occur. But you can find first message to find proto file

**Comment by IngaFeick** [comment] 2018-03-21 16:43
@invis87 you are trying to use a protobuf 2 file with a protobuf 2 class name together with the protobuf 3 version flag - that's not going to work. If you want to use protobuf 3 then you need to compile a protobuf 3 ruby file. Please look into the pull request that I mentioned above, it's README has a link to the google protobuf compiler that you need to generate a version 3 _pb.rb file. Also you need to adapt the classname in the logstash config codec section like so: 
``` class_name => "My::Super::ClassName"```
becomes 
``` class_name => "My.Super.ClassName" ```
This too is in the README in the pull request, as mentioned in my comment from 5 days ago. 
PR: https://github.com/logstash-plugins/logstash-codec-protobuf/pull/18

**Comment by invis87** [comment] 2018-03-22 11:16
@IngaFeick Thanks, I fix this.
But still have problems - my message cannot be deserialized by this plugin.
I removed fields one by one and found that problems is with `int64` type.
I end up with this message:
```
message TestMessage {
    int64 response_time                      = 1;
}
```
Deserializations results for it:
```
    -4791902657223630865l, // OK
    0l, // OK
    500l, // deserialized to 7299055   O_O
    22454353l, // deserialized to -4791902657223630865   O_O
    7299055l, // OK
    -4791902657223630865l, // OK
    (Int.MaxValue - 1).toLong, // fail
    Int.MinValue.toLong, // fail
    Int.MaxValue.toLong, // fail
    Long.MinValue, // fail
    Long.MaxValue // fail
```

Error message:
```
[FATAL] 2018-03-22 10:08:43.401 [LogStash::Runner] runner - An unexpected error occurred! {:error=>#<RuntimeError: CodedInputStream encountered a malformed varint.>, :backtrace=>["com/google/protobuf/jruby/RubyMessage.java:332:in `decode'", "/usr/share/logstash/vendor/local_gems/b638c153/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb:109:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-5.1.11/lib/logstash/inputs/kafka.rb:241:in `thread_runner'", "file:/usr/share/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/java_ext/java.lang.rb:12:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-kafka-5.1.11/lib/logstash/inputs/kafka.rb:240:in `thread_runner'"]}
```

**Comment by IngaFeick** [comment] 2018-03-22 13:08
Hi @invis87, thank you lots for your debugging, much appreciated! Happy to hear that you made the new version work 👍 .
About the error message: sadly that's out of the scope of what I can fix because it's an error generated by the underlying library. It would be great if you could raise an issue with the [google protobuf compiler project](https://github.com/google/protobuf) to have this fixed on their side. If you do please let me know so that I can follow the ticket and update our dependency to that lib accordingly. 
Thank you very much for your efforts, have a nice weekend!

**Comment by invis87** [comment] 2018-03-22 15:07
@IngaFeick Thanks to you too!
By the way - why you use `s.add_runtime_dependency 'google-protobuf', '3.5.0.pre'` pre release version? They release 3.5.2 already: https://github.com/google/protobuf/releases/tag/v3.5.2
Maybe this will fix problem :)

**Comment by invis87** [comment] 2018-03-22 15:42
I learned how to build gems 😄 ; now testing your plugin with `s.add_runtime_dependency 'google-protobuf', '3.3.0'`, cause looks like 3.5* is bugged

**Comment by IngaFeick** [comment] 2018-03-23 08:37
@invis87 please see the mentioned pull request for a comment about why we have selected this version of the lib. Thank you

**Comment by IngaFeick** [comment] 2018-03-23 16:41
@invis87 can you give me an _exact_ example of a test message that this is reproducable with? It would make sense to test this independently from logstash. If you give me one set of all values plus the binary data that you try to decode (for checking that I produce the same data) then I am happy to run this through a ruby script and see how that behaves. Thank you.

**Comment by invis87** [comment] 2018-03-26 07:56
@IngaFeick Okey. 
1. proto file: 
```
syntax = "proto3";

package com.bla.bla.bla;

message TestMessage {
    int64 response_time                      = 1;
}
```
2. bytes: `[8,-12,3]`
---
this is serialized message for `response_time = 500l`. It will be deserialized to `7299055`

**Comment by IngaFeick** [comment] 2018-03-26 09:17
@invis87 I have tested this in both a standalone script and as an rspec test for logstash and I was not able to reproduce the problem. I'm not sure though how you would even provide the 500l to an integer field. Gives me syntax errors so I went with 500 instead. Please run this on your machine and let me know the output and your (j)ruby version. Thank you.
```
#!/usr/bin/env ruby
# encoding: utf-8
require 'TestMessage_pb.rb'
pb_builder = Google::Protobuf::DescriptorPool.generated_pool.lookup("com.bla.bla.bla.TestMessage").msgclass
bin = pb_builder.encode(pb_builder.new({:response_time => 500}))
puts "Bin: #{bin.bytes.to_a}"
decoded = pb_builder.decode(bin)
puts "Decoded response_time: #{decoded.response_time}"
```

**Comment by invis87** [comment] 2018-03-26 11:26
@IngaFeick I am scala backend developer and use this: https://github.com/thesamet/sbt-protoc to compile `*.proto` file to scala `case class`. 
Int64 in protobuf is equivalent to JVM long .
---
in my logstash container i've got next output:
```
bash-4.2$ ruby --version
jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 OpenJDK 64-Bit Server VM 25.161-b14 on 1.8.0_161-b14 +indy +jit [linux-x86_64]

Bin: [8, 244, 3]
Decoded response_time: 500
```

p.s. veeeery interesting

**Comment by jorgelbg** [comment] 2018-03-26 12:44
Hi @invis87 can you provide the code for a producer that is causing the described issues? You could take the ruby script provided by @IngaFeick as an example.

**Comment by invis87** [comment] 2018-03-26 12:54
@jorgelbg my producer code is written in Scala. I can create repository special for this, if you want.

**Comment by jorgelbg** [comment] 2018-03-26 14:08
@invis87 If you can share even a small producer on your side that would greatly helpful. In our side we haven't been able to reproduce the issue.

In theory the binary representation (on the wire) of the data should be the same, because the type is not inferred from the language (scala/golang/java), but from the protobuf definition.

**Comment by invis87** [comment] 2018-03-28 20:05
@jorgelbg here it is: https://github.com/invis87/protobuf-to-kafka

**Comment by invis87** [comment] 2018-04-06 09:29
Hello! Guys, did you have a chance to test serialization?

**Comment by jorgelbg** [comment] 2018-04-16 13:40
Hey @invis87 we haven't had any time to check this yet, sorry about the delay.

**Comment by dmitring-onefactor** [comment] 2018-04-23 15:09
Hello! Guys, I'm progressing the task that @invis87 worked on. There is no bug in logstash-codec-protobuf. In the case @invis87 demonstrated there was a little misunderstanding of logstask-kafka-input plugin: he had to type `value_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"` (default value is org.apache.kafka.common.serialization.StringDeserializer which corrupts bytes while interpreting its as UTF-8 encoded string).

**Closed** 2018-04-23 15:12 UTC
